[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "python3Packages.setuptools", "python3Packages.wheel", "postgresql", "git", "git-lfs"]

[phases.install]
cmds = [
  "python -m venv .venv",
  "source .venv/bin/activate && pip install -r backend/requirements.txt"
]

[start]
cmd = "source .venv/bin/activate && cd backend && PYTHONPATH=$PYTHONPATH:$(pwd) sh railway_startup.sh" 