[phases.setup]
nixPkgs = ["nodejs", "python3", "python3Packages.pip", "python3Packages.setuptools", "python3Packages.wheel", "postgresql", "git", "git-lfs"]

[phases.install]
cmds = [
  "npm ci",
  "cd frontend && npm ci",
  "cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "npm start" 