[phases.setup]
nixPkgs = [
  "python3", 
  "python3Packages.pip", 
  "python3Packages.setuptools", 
  "python3Packages.wheel", 
  "postgresql", 
  "git", 
  "git-lfs",
  "gcc",
  "stdenv.cc"
]

[phases.install]
cmds = [
  "python -m venv .venv",
  "source .venv/bin/activate && pip install -r backend/requirements.txt"
]

[start]
cmd = "source .venv/bin/activate && cd backend && PYTHONPATH=$PYTHONPATH:$(pwd) LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH sh railway_startup.sh" 