[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "sh railway_startup.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[nixpacks]
platformEnv = ["PYTHONPATH=."]

[nixpacks.setup]
cmds = ["apt-get update && apt-get install -y git git-lfs"]

[nixpacks.plan.phases.build]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"] 