# Railway configuration for backend service

[build]
builder = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
healthcheckInterval = 30
startCommand = "sh railway_startup.sh" 